### ISSUE TITLE
yarn start does not work on windows

### ISSUE THREAD

**Issue by rafpran** [paytonrules/learn-reactive-extensions#3]
See https://stackoverflow.com/questions/30950032/how-can-i-run-multiple-npm-scripts-in-parallel

solution:
`yarn add -D concurrently `

`"start": "concurrently --kill-others \"json-server --watch mock-data/db.json --port 3001 --host 0.0.0.0\" \"react-scripts start\"",`

**Comment by paytonrules** [comment]
Thanks! - This worked swimmingly.
